name:                fast-pandoc
version:             0.1.0.0
license:             GPL3
author:              "Daniel Gnoutcheff"
maintainer:          "gnoutchd@softwarefreedom.org"
copyright:           "2021 Software Freedom Law Center"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         "Faster pandoc plugin for IkiWiki"

dependencies:
- base >= 4.7 && < 5
- mtl
- exceptions
- bytestring
- text
- pandoc
- haxr
- HaXml
- polyparse
- filepath

executables:
  fast-pandoc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
